// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountUsers             string
	Accounts                 string
	Attendees                string
	Attributes               string
	Customers                string
	DiscountCodes            string
	EventAttributes          string
	EventQuestions           string
	Events                   string
	QuestionAnswers          string
	Questions                string
	TicketAttributes         string
	TicketQuestions          string
	Tickets                  string
	TransactionAttributes    string
	TransactionDiscountCodes string
	TransactionItems         string
	Transactions             string
	Users                    string
}{
	AccountUsers:             "account_users",
	Accounts:                 "accounts",
	Attendees:                "attendees",
	Attributes:               "attributes",
	Customers:                "customers",
	DiscountCodes:            "discount_codes",
	EventAttributes:          "event_attributes",
	EventQuestions:           "event_questions",
	Events:                   "events",
	QuestionAnswers:          "question_answers",
	Questions:                "questions",
	TicketAttributes:         "ticket_attributes",
	TicketQuestions:          "ticket_questions",
	Tickets:                  "tickets",
	TransactionAttributes:    "transaction_attributes",
	TransactionDiscountCodes: "transaction_discount_codes",
	TransactionItems:         "transaction_items",
	Transactions:             "transactions",
	Users:                    "users",
}
