// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// EventQuestion is an object representing the database table.
type EventQuestion struct {
	ID         int `boil:"id" json:"id" toml:"id" yaml:"id"`
	EventID    int `boil:"event_id" json:"event_id" toml:"event_id" yaml:"event_id"`
	QuestionID int `boil:"question_id" json:"question_id" toml:"question_id" yaml:"question_id"`

	R *eventQuestionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventQuestionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventQuestionColumns = struct {
	ID         string
	EventID    string
	QuestionID string
}{
	ID:         "id",
	EventID:    "event_id",
	QuestionID: "question_id",
}

// EventQuestionRels is where relationship names are stored.
var EventQuestionRels = struct {
	Event    string
	Question string
}{
	Event:    "Event",
	Question: "Question",
}

// eventQuestionR is where relationships are stored.
type eventQuestionR struct {
	Event    *Event
	Question *Question
}

// NewStruct creates a new relationship struct
func (*eventQuestionR) NewStruct() *eventQuestionR {
	return &eventQuestionR{}
}

// eventQuestionL is where Load methods for each relationship are stored.
type eventQuestionL struct{}

var (
	eventQuestionColumns               = []string{"id", "event_id", "question_id"}
	eventQuestionColumnsWithoutDefault = []string{"event_id", "question_id"}
	eventQuestionColumnsWithDefault    = []string{"id"}
	eventQuestionPrimaryKeyColumns     = []string{"id"}
)

type (
	// EventQuestionSlice is an alias for a slice of pointers to EventQuestion.
	// This should generally be used opposed to []EventQuestion.
	EventQuestionSlice []*EventQuestion
	// EventQuestionHook is the signature for custom EventQuestion hook methods
	EventQuestionHook func(boil.Executor, *EventQuestion) error

	eventQuestionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventQuestionType                 = reflect.TypeOf(&EventQuestion{})
	eventQuestionMapping              = queries.MakeStructMapping(eventQuestionType)
	eventQuestionPrimaryKeyMapping, _ = queries.BindMapping(eventQuestionType, eventQuestionMapping, eventQuestionPrimaryKeyColumns)
	eventQuestionInsertCacheMut       sync.RWMutex
	eventQuestionInsertCache          = make(map[string]insertCache)
	eventQuestionUpdateCacheMut       sync.RWMutex
	eventQuestionUpdateCache          = make(map[string]updateCache)
	eventQuestionUpsertCacheMut       sync.RWMutex
	eventQuestionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var eventQuestionBeforeInsertHooks []EventQuestionHook
var eventQuestionBeforeUpdateHooks []EventQuestionHook
var eventQuestionBeforeDeleteHooks []EventQuestionHook
var eventQuestionBeforeUpsertHooks []EventQuestionHook

var eventQuestionAfterInsertHooks []EventQuestionHook
var eventQuestionAfterSelectHooks []EventQuestionHook
var eventQuestionAfterUpdateHooks []EventQuestionHook
var eventQuestionAfterDeleteHooks []EventQuestionHook
var eventQuestionAfterUpsertHooks []EventQuestionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventQuestion) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventQuestion) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventQuestion) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventQuestion) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventQuestion) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventQuestion) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventQuestion) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventQuestion) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventQuestion) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventQuestionAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventQuestionHook registers your hook function for all future operations.
func AddEventQuestionHook(hookPoint boil.HookPoint, eventQuestionHook EventQuestionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		eventQuestionBeforeInsertHooks = append(eventQuestionBeforeInsertHooks, eventQuestionHook)
	case boil.BeforeUpdateHook:
		eventQuestionBeforeUpdateHooks = append(eventQuestionBeforeUpdateHooks, eventQuestionHook)
	case boil.BeforeDeleteHook:
		eventQuestionBeforeDeleteHooks = append(eventQuestionBeforeDeleteHooks, eventQuestionHook)
	case boil.BeforeUpsertHook:
		eventQuestionBeforeUpsertHooks = append(eventQuestionBeforeUpsertHooks, eventQuestionHook)
	case boil.AfterInsertHook:
		eventQuestionAfterInsertHooks = append(eventQuestionAfterInsertHooks, eventQuestionHook)
	case boil.AfterSelectHook:
		eventQuestionAfterSelectHooks = append(eventQuestionAfterSelectHooks, eventQuestionHook)
	case boil.AfterUpdateHook:
		eventQuestionAfterUpdateHooks = append(eventQuestionAfterUpdateHooks, eventQuestionHook)
	case boil.AfterDeleteHook:
		eventQuestionAfterDeleteHooks = append(eventQuestionAfterDeleteHooks, eventQuestionHook)
	case boil.AfterUpsertHook:
		eventQuestionAfterUpsertHooks = append(eventQuestionAfterUpsertHooks, eventQuestionHook)
	}
}

// One returns a single eventQuestion record from the query.
func (q eventQuestionQuery) One(exec boil.Executor) (*EventQuestion, error) {
	o := &EventQuestion{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for event_questions")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventQuestion records from the query.
func (q eventQuestionQuery) All(exec boil.Executor) (EventQuestionSlice, error) {
	var o []*EventQuestion

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventQuestion slice")
	}

	if len(eventQuestionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventQuestion records in the query.
func (q eventQuestionQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count event_questions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventQuestionQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if event_questions exists")
	}

	return count > 0, nil
}

// Event pointed to by the foreign key.
func (o *EventQuestion) Event(mods ...qm.QueryMod) eventQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.EventID),
	}

	queryMods = append(queryMods, mods...)

	query := Events(queryMods...)
	queries.SetFrom(query.Query, "\"events\"")

	return query
}

// Question pointed to by the foreign key.
func (o *EventQuestion) Question(mods ...qm.QueryMod) questionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.QuestionID),
	}

	queryMods = append(queryMods, mods...)

	query := Questions(queryMods...)
	queries.SetFrom(query.Query, "\"questions\"")

	return query
}

// LoadEvent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventQuestionL) LoadEvent(e boil.Executor, singular bool, maybeEventQuestion interface{}, mods queries.Applicator) error {
	var slice []*EventQuestion
	var object *EventQuestion

	if singular {
		object = maybeEventQuestion.(*EventQuestion)
	} else {
		slice = *maybeEventQuestion.(*[]*EventQuestion)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &eventQuestionR{}
		}
		args = append(args, object.EventID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventQuestionR{}
			}

			for _, a := range args {
				if a == obj.EventID {
					continue Outer
				}
			}

			args = append(args, obj.EventID)
		}
	}

	query := NewQuery(qm.From(`events`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Event")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Event")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventQuestionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Event = foreign
		if foreign.R == nil {
			foreign.R = &eventR{}
		}
		foreign.R.EventQuestions = append(foreign.R.EventQuestions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EventID == foreign.ID {
				local.R.Event = foreign
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.EventQuestions = append(foreign.R.EventQuestions, local)
				break
			}
		}
	}

	return nil
}

// LoadQuestion allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventQuestionL) LoadQuestion(e boil.Executor, singular bool, maybeEventQuestion interface{}, mods queries.Applicator) error {
	var slice []*EventQuestion
	var object *EventQuestion

	if singular {
		object = maybeEventQuestion.(*EventQuestion)
	} else {
		slice = *maybeEventQuestion.(*[]*EventQuestion)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &eventQuestionR{}
		}
		args = append(args, object.QuestionID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventQuestionR{}
			}

			for _, a := range args {
				if a == obj.QuestionID {
					continue Outer
				}
			}

			args = append(args, obj.QuestionID)
		}
	}

	query := NewQuery(qm.From(`questions`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Question")
	}

	var resultSlice []*Question
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Question")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for questions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for questions")
	}

	if len(eventQuestionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Question = foreign
		if foreign.R == nil {
			foreign.R = &questionR{}
		}
		foreign.R.EventQuestions = append(foreign.R.EventQuestions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.QuestionID == foreign.ID {
				local.R.Question = foreign
				if foreign.R == nil {
					foreign.R = &questionR{}
				}
				foreign.R.EventQuestions = append(foreign.R.EventQuestions, local)
				break
			}
		}
	}

	return nil
}

// SetEvent of the eventQuestion to the related item.
// Sets o.R.Event to related.
// Adds o to related.R.EventQuestions.
func (o *EventQuestion) SetEvent(exec boil.Executor, insert bool, related *Event) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"event_questions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"event_id"}),
		strmangle.WhereClause("\"", "\"", 2, eventQuestionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EventID = related.ID
	if o.R == nil {
		o.R = &eventQuestionR{
			Event: related,
		}
	} else {
		o.R.Event = related
	}

	if related.R == nil {
		related.R = &eventR{
			EventQuestions: EventQuestionSlice{o},
		}
	} else {
		related.R.EventQuestions = append(related.R.EventQuestions, o)
	}

	return nil
}

// SetQuestion of the eventQuestion to the related item.
// Sets o.R.Question to related.
// Adds o to related.R.EventQuestions.
func (o *EventQuestion) SetQuestion(exec boil.Executor, insert bool, related *Question) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"event_questions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"question_id"}),
		strmangle.WhereClause("\"", "\"", 2, eventQuestionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.QuestionID = related.ID
	if o.R == nil {
		o.R = &eventQuestionR{
			Question: related,
		}
	} else {
		o.R.Question = related
	}

	if related.R == nil {
		related.R = &questionR{
			EventQuestions: EventQuestionSlice{o},
		}
	} else {
		related.R.EventQuestions = append(related.R.EventQuestions, o)
	}

	return nil
}

// EventQuestions retrieves all the records using an executor.
func EventQuestions(mods ...qm.QueryMod) eventQuestionQuery {
	mods = append(mods, qm.From("\"event_questions\""))
	return eventQuestionQuery{NewQuery(mods...)}
}

// FindEventQuestion retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventQuestion(exec boil.Executor, iD int, selectCols ...string) (*EventQuestion, error) {
	eventQuestionObj := &EventQuestion{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"event_questions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, eventQuestionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from event_questions")
	}

	return eventQuestionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventQuestion) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no event_questions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventQuestionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventQuestionInsertCacheMut.RLock()
	cache, cached := eventQuestionInsertCache[key]
	eventQuestionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventQuestionColumns,
			eventQuestionColumnsWithDefault,
			eventQuestionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventQuestionType, eventQuestionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventQuestionType, eventQuestionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"event_questions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"event_questions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into event_questions")
	}

	if !cached {
		eventQuestionInsertCacheMut.Lock()
		eventQuestionInsertCache[key] = cache
		eventQuestionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the EventQuestion.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventQuestion) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventQuestionUpdateCacheMut.RLock()
	cache, cached := eventQuestionUpdateCache[key]
	eventQuestionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventQuestionColumns,
			eventQuestionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update event_questions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"event_questions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventQuestionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventQuestionType, eventQuestionMapping, append(wl, eventQuestionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update event_questions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for event_questions")
	}

	if !cached {
		eventQuestionUpdateCacheMut.Lock()
		eventQuestionUpdateCache[key] = cache
		eventQuestionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventQuestionQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for event_questions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for event_questions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventQuestionSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventQuestionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"event_questions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventQuestionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in eventQuestion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all eventQuestion")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventQuestion) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no event_questions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventQuestionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventQuestionUpsertCacheMut.RLock()
	cache, cached := eventQuestionUpsertCache[key]
	eventQuestionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			eventQuestionColumns,
			eventQuestionColumnsWithDefault,
			eventQuestionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			eventQuestionColumns,
			eventQuestionPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert event_questions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(eventQuestionPrimaryKeyColumns))
			copy(conflict, eventQuestionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"event_questions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(eventQuestionType, eventQuestionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventQuestionType, eventQuestionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert event_questions")
	}

	if !cached {
		eventQuestionUpsertCacheMut.Lock()
		eventQuestionUpsertCache[key] = cache
		eventQuestionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single EventQuestion record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventQuestion) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventQuestion provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventQuestionPrimaryKeyMapping)
	sql := "DELETE FROM \"event_questions\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from event_questions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for event_questions")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventQuestionQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no eventQuestionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from event_questions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_questions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventQuestionSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventQuestion slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(eventQuestionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventQuestionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"event_questions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventQuestionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eventQuestion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_questions")
	}

	if len(eventQuestionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventQuestion) Reload(exec boil.Executor) error {
	ret, err := FindEventQuestion(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventQuestionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventQuestionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventQuestionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"event_questions\".* FROM \"event_questions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventQuestionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventQuestionSlice")
	}

	*o = slice

	return nil
}

// EventQuestionExists checks if the EventQuestion row exists.
func EventQuestionExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"event_questions\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if event_questions exists")
	}

	return exists, nil
}
