// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEventQuestions(t *testing.T) {
	t.Parallel()

	query := EventQuestions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEventQuestionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEventQuestionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EventQuestions().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEventQuestionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EventQuestionSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEventQuestionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EventQuestionExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if EventQuestion exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EventQuestionExists to return true, but got false.")
	}
}

func testEventQuestionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	eventQuestionFound, err := FindEventQuestion(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if eventQuestionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEventQuestionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EventQuestions().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testEventQuestionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EventQuestions().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEventQuestionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	eventQuestionOne := &EventQuestion{}
	eventQuestionTwo := &EventQuestion{}
	if err = randomize.Struct(seed, eventQuestionOne, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}
	if err = randomize.Struct(seed, eventQuestionTwo, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = eventQuestionOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = eventQuestionTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EventQuestions().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEventQuestionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	eventQuestionOne := &EventQuestion{}
	eventQuestionTwo := &EventQuestion{}
	if err = randomize.Struct(seed, eventQuestionOne, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}
	if err = randomize.Struct(seed, eventQuestionTwo, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = eventQuestionOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = eventQuestionTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func eventQuestionBeforeInsertHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionAfterInsertHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionAfterSelectHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionBeforeUpdateHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionAfterUpdateHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionBeforeDeleteHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionAfterDeleteHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionBeforeUpsertHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func eventQuestionAfterUpsertHook(e boil.Executor, o *EventQuestion) error {
	*o = EventQuestion{}
	return nil
}

func testEventQuestionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &EventQuestion{}
	o := &EventQuestion{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EventQuestion object: %s", err)
	}

	AddEventQuestionHook(boil.BeforeInsertHook, eventQuestionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	eventQuestionBeforeInsertHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.AfterInsertHook, eventQuestionAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	eventQuestionAfterInsertHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.AfterSelectHook, eventQuestionAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	eventQuestionAfterSelectHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.BeforeUpdateHook, eventQuestionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	eventQuestionBeforeUpdateHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.AfterUpdateHook, eventQuestionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	eventQuestionAfterUpdateHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.BeforeDeleteHook, eventQuestionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	eventQuestionBeforeDeleteHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.AfterDeleteHook, eventQuestionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	eventQuestionAfterDeleteHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.BeforeUpsertHook, eventQuestionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	eventQuestionBeforeUpsertHooks = []EventQuestionHook{}

	AddEventQuestionHook(boil.AfterUpsertHook, eventQuestionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	eventQuestionAfterUpsertHooks = []EventQuestionHook{}
}

func testEventQuestionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEventQuestionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(eventQuestionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEventQuestionToOneEventUsingEvent(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local EventQuestion
	var foreign Event

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, eventDBTypes, false, eventColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Event struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.EventID = foreign.ID
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Event().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := EventQuestionSlice{&local}
	if err = local.L.LoadEvent(tx, false, (*[]*EventQuestion)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Event == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Event = nil
	if err = local.L.LoadEvent(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Event == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testEventQuestionToOneQuestionUsingQuestion(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local EventQuestion
	var foreign Question

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, eventQuestionDBTypes, false, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, questionDBTypes, false, questionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Question struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.QuestionID = foreign.ID
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Question().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := EventQuestionSlice{&local}
	if err = local.L.LoadQuestion(tx, false, (*[]*EventQuestion)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Question == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Question = nil
	if err = local.L.LoadQuestion(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Question == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testEventQuestionToOneSetOpEventUsingEvent(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a EventQuestion
	var b, c Event

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, eventQuestionDBTypes, false, strmangle.SetComplement(eventQuestionPrimaryKeyColumns, eventQuestionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, eventDBTypes, false, strmangle.SetComplement(eventPrimaryKeyColumns, eventColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, eventDBTypes, false, strmangle.SetComplement(eventPrimaryKeyColumns, eventColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Event{&b, &c} {
		err = a.SetEvent(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Event != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.EventQuestions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.EventID != x.ID {
			t.Error("foreign key was wrong value", a.EventID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.EventID))
		reflect.Indirect(reflect.ValueOf(&a.EventID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.EventID != x.ID {
			t.Error("foreign key was wrong value", a.EventID, x.ID)
		}
	}
}
func testEventQuestionToOneSetOpQuestionUsingQuestion(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a EventQuestion
	var b, c Question

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, eventQuestionDBTypes, false, strmangle.SetComplement(eventQuestionPrimaryKeyColumns, eventQuestionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, questionDBTypes, false, strmangle.SetComplement(questionPrimaryKeyColumns, questionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, questionDBTypes, false, strmangle.SetComplement(questionPrimaryKeyColumns, questionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Question{&b, &c} {
		err = a.SetQuestion(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Question != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.EventQuestions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.QuestionID != x.ID {
			t.Error("foreign key was wrong value", a.QuestionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.QuestionID))
		reflect.Indirect(reflect.ValueOf(&a.QuestionID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.QuestionID != x.ID {
			t.Error("foreign key was wrong value", a.QuestionID, x.ID)
		}
	}
}

func testEventQuestionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testEventQuestionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EventQuestionSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testEventQuestionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EventQuestions().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	eventQuestionDBTypes = map[string]string{`EventID`: `integer`, `ID`: `integer`, `QuestionID`: `integer`}
	_                    = bytes.MinRead
)

func testEventQuestionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(eventQuestionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(eventQuestionColumns) == len(eventQuestionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEventQuestionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(eventQuestionColumns) == len(eventQuestionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EventQuestion{}
	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, eventQuestionDBTypes, true, eventQuestionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(eventQuestionColumns, eventQuestionPrimaryKeyColumns) {
		fields = eventQuestionColumns
	} else {
		fields = strmangle.SetComplement(
			eventQuestionColumns,
			eventQuestionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EventQuestionSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEventQuestionsUpsert(t *testing.T) {
	t.Parallel()

	if len(eventQuestionColumns) == len(eventQuestionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EventQuestion{}
	if err = randomize.Struct(seed, &o, eventQuestionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EventQuestion: %s", err)
	}

	count, err := EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, eventQuestionDBTypes, false, eventQuestionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EventQuestion struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EventQuestion: %s", err)
	}

	count, err = EventQuestions().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
